name: Hengjiu Kang
author: Hengjiu Kang
baseurl: ""
description: My Showcase
github: http://www.github.com/khjtony
facebook: https://www.facebook.com/hengjiu.kang
linkedin: https://www.linkedin.com/hp/?dnr=DylH0KmN16e6ZDxuDybr-FYW6DiHZltw3LFk
email: khjtony[at]gmail.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
# markdown: redcarpet
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

      